### ISSUE TITLE
Unable to load `quantized` models 

### ISSUE THREAD

**Issue by kishorekaruppusamy** [absadiki/pywhispercpp#33]
I am trying to load whisper tiny quantized version ( ggml-tiny-q5_1.bin)
i trying this using jupyter kernal in visual studio code
But when i try to run 
`model = Model('./models/quantized/ggml-tiny-q5_1.bin', print_progress=False)`
Kernal is dying ( unable to load quantized model ) remaining unquantized models are working file seems to be issue in quantized version

![image](https://github.com/abdeladim-s/pywhispercpp/assets/103121724/9b65b8ef-db9e-4997-b9ea-aba8a89430ac)

Kindly need someone help !!!

**Comment by absadiki** [comment]
@kishorekaruppusamy, I just pushed a new version `1.2.0` to PYPI that supports the latest version of `whisper.cpp`. 
Quantized models should be working now.

Let me know if you still have any issues ?

**Comment by kishorekaruppusamy** [comment]
> @kishorekaruppusamy, I just pushed a new version `1.2.0` to PYPI that supports the latest version of `whisper.cpp`. Quantized models should be working now.
> 
> Let me know if you still have any issues ?

lets check ...

**Comment by kishorekaruppusamy** [comment]
> > @kishorekaruppusamy, I just pushed a new version `1.2.0` to PYPI that supports the latest version of `whisper.cpp`. Quantized models should be working now.
> > Let me know if you still have any issues ?
> 
> lets check ...

Thanks for the changes !!!, it working now 💥
