### ISSUE TITLE
Model class is not supporting relative paths to files

### ISSUE THREAD

**Issue by guschin** [absadiki/pywhispercpp#4]
I'm experimenting with your library, and I've noticed that the Model class is not supporting relative paths to files. Here is the traceback.

```
In [5]: asr_result = model.transcribe("../../audio1470766962.wav")
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[5], line 1
----> 1 asr_result = model.transcribe("../../audio1470766962.wav")

File ~/whisper/lib/python3.10/site-packages/pywhispercpp/model.py:118, in Model.transcribe(self, media, n_processors, new_segment_callback, **params)
    116     media_path = Path(media).absolute()
    117     if not media_path.exists():
--> 118         raise FileNotFoundError(media)
    119     audio = self._load_audio(media_path)
    120 # update params if any

FileNotFoundError: ../../audio1470766962.wav
```

I assume this is because of the using **absolute** method from _pathlib_. If I'm reading the [documentation](https://docs.python.org/3/library/pathlib.html#pathlib.Path.resolve) correctly, using **resolve** method instead of **absoulte** will resolve (pun intended) the issue 🙂

Here is the example

```
In [3]: pathlib.Path('../audio1470766962.wav').absolute()
Out[3]: PosixPath('/Users/guschin/whisper/../audio1470766962.wav')

In [4]: pathlib.Path('../audio1470766962.wav').resolve()
Out[4]: PosixPath('/Users/guschin/audio1470766962.wav')
```

Would you consider this change, please? I can send you a PR.

**Comment by absadiki** [comment]
Yes Sure, PR is more than welcome :smile: 
Thanks @guschin for pointing that out.

**Comment by absadiki** [comment]
hi @guschin,
I have resolved the issue by using `resolve` as you suggested :slightly_smiling_face:

Please give it a try and let me know if the problem persists ?

**Comment by guschin** [comment]
Yes, now it works as expected! Thanks for the swift response and for the great library you developed 😀

**Comment by absadiki** [comment]
You are welcome @guschin
'Glad you find it useful :smile:
