### ISSUE TITLE
Add vulkan support

### ISSUE THREAD

**Issue by thewh1teagle** [absadiki/pywhispercpp#41]
Recently whisper.cpp added vulkan for linux/windows.
It works on almost every GPU.
How can we build pywhispercpp with latest whisper.cpp and enable GGML_VULKAN flag in cmake?

**Comment by absadiki** [comment]
I don't see any `VULKAN` flag in the `whisper.cpp` repo
[Here](https://github.com/ggerganov/whisper.cpp/blob/c7b6988678779901d02ceba1a8212d2c9908956e/CMakeLists.txt#L84C3-L94C99) are all the supported flags!

**Comment by thewh1teagle** [comment]
It's added but not released yet to whisper.cpp

https://github.com/ggerganov/whisper.cpp/blob/master/ggml/CMakeLists.txt#L135

Maybe I can build pywhispercpp with latest whisper.cpp and pass this option?
