### ISSUE TITLE
Proposal: Enable CoreML / CUDA by default

### ISSUE THREAD

**Issue by UsernamesLame** [absadiki/pywhispercpp#45]
Just a proposal, enable all the acceleration backends that *typically* would be used by default. They barely increase the size of the whisper shared library and would save a lot of headache. 

Thoughts?

**Comment by thewh1teagle** [comment]
Cuda is not supported without nvidia card.

**Comment by UsernamesLame** [comment]
I know. If we enable it by default, whisper.cpp will try and use it only if available.

**Comment by thewh1teagle** [comment]
> I know. If we enable it by default, whisper.cpp will try and use it only if available.

I wish. afaik it's will crash if nvidia enabled but not supported on device.
Also the nvidia DLL will be much heavier

**Comment by absadiki** [comment]
@UsernamesLame, as @thewh1teagle said, If you try to compile against CUDA, for example, and CUDA is not installed, it will most likely crash.

Even if it works, assuming `whisper.cpp` just ignores CUDA if it's not installed, it's not a good practice in my opinion, especially if someone wants a CPU-only version or has more than one accelerator. So, I think sticking with `whisper.cpp` defaults and adding the desired flag during the pip install is more practical and will work for everyone!"

**Comment by UsernamesLame** [comment]
> @UsernamesLame, as @thewh1teagle said, If you try to compile against CUDA, for example, and CUDA is not installed, it will most likely crash.
> 
> Even if it works, assuming `whisper.cpp` just ignores CUDA if it's not installed, it's not a good practice in my opinion, especially if someone wants a CPU-only version or has more than one accelerator. So, I think sticking with `whisper.cpp` defaults and adding the desired flag during the pip install is more practical and will work for everyone!"

It shouldn't crash, that sounds like a upstream bug. From what I understand, it will search for CUDA devices to use if CUDA is compiled in. Maybe I need to make a FR with whisper.cpp?

As for people who want CPU only inference, doesn't whisper.cpp expose flags to disable GPU inference / select device?

**Comment by absadiki** [comment]
@UsernamesLame, Even if the compilation went successful, it will probably crash at runtime looking for cuda libraries.
Yes, in that case, you can disable cuda and whisper.cpp will most likely fall back to CPU, but this is not practical in my opinion. 

That being said, I think now with the Vulkan backend this use case will be supported.

**Comment by UsernamesLame** [comment]
> @UsernamesLame, Even if the compilation went successful, it will probably crash at runtime looking for cuda libraries. Yes, in that case, you can disable cuda and whisper.cpp will most likely fall back to CPU, but this is not practical in my opinion.
> 
> That being said, I think now with the Vulkan backend this use case will be supported.

I tried compiling with CUDA today and ran it (I have a NVIDIA GPU) and it worked! It worked even when I didn't have the CUDA supporting libs installed.

But fair points. Lets try and fix the slowness of it on the CPU now. I'm working with 6c/12t and it's hit and miss on speed. My small patch *should* help *the tiniest bit* but I have a feeling if I can write a pickling script to spit out numpy arrays instead of wav files, we can get some increases in performance.

**Comment by absadiki** [comment]
@UsernamesLame, If it's today then I think it's working probably because of Vulkan. 

It's normal that running on CPU will be a bit slow, especially for bigger models, but if if it's super slow compared to `whisper.cpp`  you can close this one and open a new issue for it!

**Comment by UsernamesLame** [comment]
> @UsernamesLame, If it's today then I think it's working probably because of Vulkan. 
> 
> 
> 
> It's normal that running on CPU will be a bit slow, especially for bigger models, but if if it's super slow compared to `whisper.cpp`  you can close this one and open a new issue for it!
> 
> 

I'll close this one and start a new one. Idk if I'll make any pull resets tonight. 

For now I can start a thread.
