### ISSUE TITLE
Transcription from .wav file does not work

### ISSUE THREAD

**Issue by KianRK** [absadiki/pywhispercpp#89]
I have a short audio file in .wav format where I clearly say "Answer with just the result: 2+2". But when I transcribe it with base.en model the text of the segments contain [Music][Music][Music][ Silence ].

There are no background noises on the audio and it works perfectly fine when I use an mp3 file with the same content.

I recorded both audios with ffmpeg.

**Comment by absadiki** [comment]
@KianRK, The Whisper model is trained on 16kHz mono files, so make sure that your .wav file is recorded at this sample rate and in mono format. When you are using the .mp3 file, FFmpeg takes care of this conversion under the hood, which is likely why it is working.

**Comment by KianRK** [comment]
@absadiki Yes, that was the problem. Also I had to set the bitrate to 256 kbps, but then it worked fine. Thank you.

**Comment by absadiki** [comment]
@KianRK, Sounds good! Feel free to reopen the issue if you encounter any further problems.
